web:
  build: .
  # command: 'bash -c ''/usr/bin/env gunicorn --workers=3 --threads=20 --log-file - wsgi:application'''
  # working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - .:/stuff
